[package]
name = "wgmeeting_github_ircbot"
version = "0.3.6"
authors = ["L. David Baron <dbaron@dbaron.org>"]
build = "build.rs"

[dependencies]
futures = "0.1"
log = "0.4"
env_logger = "0.5"
lazy_static = "1.1"
regex = "1.0"
tokio-core = "0.1" # should upgrade from tokio-core to tokio once hubcaps supports it
tokio-io = "0.1"
tokio-codec = "0.1"
hubcaps = "0.4.6"
hyper = "0.11" # should update to 0.12
hyper-tls = "0.1" # should update to 0.3
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diff = "0.1"

[dependencies.irc]
version = "0.13"
default-features = false
features = ["ctcp", "json"]
